### PR TITLE
Feat: Add JCASC managed config files

### PR DESCRIPTION
**Pull request by eb-oss**
Issue-ID: LF-Jira RELENG-3741
Signed-off-by: Eric Ball <eball@linuxfoundation.org>

### CODE REVIEW

**Comment by eb-oss** [comment]
recheck

**Review by tykeal — COMMENTED** [review]
I see no content entries for the pipconf and jenkins-log-archives-settings files. Have you tested to make sure it produces correct jcasc for empty files doing this?

**Comment by eb-oss** [comment]
Yes, my tests on the Acumos sandbox showed that this is a valid config.

**Review by tykeal — APPROVED** [review]

**Comment by tykeal** [comment]
> Yes, my tests on the Acumos sandbox showed that this is a valid config.

Great! Maybe I wrote that script better than I thought. Either that, or Jenkins is dealing with stuff better than I expect ;)

**Pull request merged**
