### PR TITLE
Add back branches to build in SCM section

### PR DESCRIPTION
**Pull request by Al-tekreeti**
Signed-off-by: Mustafa Al-tekreeti <mmaj1976@gmail.com>

### CODE REVIEW

**Comment by Al-tekreeti** [comment]
I am still getting "Jenkinsfile not found" error. It looks like Jenkins builder does not figure out the right branch, so I am returning it to the SCM section. Thanks!

**Comment by eb-oss** [comment]
This puts us right back where we started, with the pipeline checking out the target head rather than the feature branch.

**Comment by Al-tekreeti** [comment]
What do you think? Why Jenkins is missing the path to Jenkinsfile. This is the only part that we tell the name of the branch in the yaml file.

**Comment by eb-oss** [comment]
Without any branch specifier, it's looking through all of the PRs and building PR 5. Looking at the oldest PRs, it seems that the others around this are merged, but this one was closed. So I'm guessing it ends up just taking the first non-merged PR it finds.

What you may want to do is take a parameter that's passed by the GHPRB plugin, and use that as the refspec. That way, when a PR triggers the build, the scm section will check out the code from that PR. However, this introduces the issue using the Jenkinsfile in the feature branch, rather than the one in master. https://jenkins.lfedge.org/job/anax-build-pipeline/10/parameters/

You may want to take a look at how other people write their pipeline jobs for this purpose. Connecting a pipeline to a Github repo is certainly not an uncommon task, so there should be plenty of info available.

**Comment by Al-tekreeti** [comment]
This is how to define those sections according to GHPRB plugin documents:

set "refspec" to +refs/pull/*:refs/remotes/origin/pr/*

In "Branch Specifier", enter ${sha1}, or if you want to use the actual commit in the pull request, use ${ghprbActualCommit}

**Comment by eb-oss** [comment]
Ah, there you go. So ${sha1} should work. You'll want to put it in double quotes and exclude the curly braces, so that it doesn't get picked up by JJB as an internal variable.

**Comment by Al-tekreeti** [comment]
Okay I will try right now. Thanks!

**Review by eb-oss — APPROVED** [review]

**Pull request merged**
