### PR TITLE
Remove branches to build from SCM section

### PR DESCRIPTION
**Pull request by Al-tekreeti**
Signed-off-by: Mustafa Al-tekreeti <mmaj1976@gmail.com>

### CODE REVIEW

**Review by eb-oss — COMMENTED** [review]
Why are you pulling credentials/auth-id from scm and triggers?

**Comment by Al-tekreeti** [comment]
credentials-id is still there in SCM section and I thought auth-id is optional in the Trigger section.

**Review by eb-oss — CHANGES_REQUESTED** [review]
credentials-id has also been removed, and auth-id is required for creating hooks. Please re-add both.

**Comment by Al-tekreeti** [comment]
I re-added them. Thanks!

**Review by eb-oss — APPROVED** [review]

**Pull request merged**
