### PR TITLE
Configuring the anax-build-pipeline

### PR DESCRIPTION
**Pull request by Al-tekreeti**
Signed-off-by: Mustafa <mmaj1976@gmail.com>

### CODE REVIEW

**Review by eb-oss — CHANGES_REQUESTED** [review]
Just one tiny change needed, and then you're good to go: Please add your last name to the signed-off-by line. You'll need to amend your commit and then force-push your feature branch.

**Comment by Al-tekreeti** [comment]
I did "git commit -s -m" for the last commit, so it should be signed off by my username. Please, can you explain more why I need to amend last commit?

**Comment by eb-oss** [comment]
> I did "git commit -s -m" for the last commit, so it should be signed off by my username. Please, can you explain more why I need to amend last commit?

It doesn't contain your full name. You probably need to edit your git config.

**Review by eb-oss — APPROVED** [review]

**Review by eb-oss — CHANGES_REQUESTED** [review]
Sorry, one more thing I didn't catch before: commit message should be in the imperative mood. It could also be more informative. Something like:
`Add credentials-id and GHPR trigger for anax`

**Review by eb-oss — CHANGES_REQUESTED** [review]
Imperative mood should be in the form of a command or request, not an action. Which effectively means: use "Add" rather than "Adding".
https://chris.beams.io/posts/git-commit/

**Comment by Al-tekreeti** [comment]
Thanks for the article, very informative.

**Review by eb-oss — APPROVED** [review]

**Pull request merged**
